# verion: '3.8'

# services:
#   nginx:
#     image: nginx:latest
#     container__name: nginx
#     hostname: nginx
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     ports:
#       - 80:80
#     retart: unless-stopped

#   uwsgi-1:
#     build: .
#     image: aprenderdevops/uwsgi:latest
#     container_name: uwsgi-1
#     hostname: uwsgi-1
#     volumes:
#       - ./data:/data
#     restart: unless-stopped

#   uwsgi-2:
#     image: aprenderdevops/uwsgi:latest
#     container_name: uwsgi-2
#     hostname: uwsgi-2
#     volumes:
#       - ./data:/data
#     restart: uless-stopped

# version: "3.8"

services:
  integrens:
    environment:
      - KEY-SECRET=claveSuperHyperMegaSecreta1234567890adminroot
    container_name: web_personal
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app