version: "3.8"

services:
  integrens:
    environment:
      - KEY-SECRET=claveSuperHyperMegaSecreta1234567890adminroot
    container_name: web_personal
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app
